[global]
  workgroup = WORKGROUP
  server min protocol = SMB2_02
  server max protocol = SMB3_11
  smb ports = 445
  security = user
  map to guest = never
  load printers = no
  printing = bsd
  disable spoolss = yes
  log level = 1

[tmp]
  path = /share
  read only = no
  guest ok = no
  force user = smbuser
  create mask = 0777
  directory mask = 0777

[tmp2]
  path = /share
  read only = yes
  guest ok = no
  force user = smbuser
